### ISSUE TITLE
generated typography-placeholder contents are incorrect

### ISSUE THREAD

**Issue by mfranzke** [db-ui/base#172]
The generated `build/scss/_typography-placeholder.scss` files contents seem to be incorrect – where we had some selectors like the following previously:
```SCSS
%db-normal-headline-3xl{

	line-height: $db-typography-normal-mobile-headline-3xlarge-line-height;
	font-size: $db-typography-normal-mobile-headline-3xlarge-font-size;

    &-light,
    &[data-variant="light"] {
        font-weight: 300;
    }
	
	@media only screen and (min-width: $db-screens-md) {
		line-height: $db-typography-normal-tablet-headline-3xlarge-line-height;
		font-size: $db-typography-normal-tablet-headline-3xlarge-font-size;}

	@media only screen and (min-width: $db-screens-lg) {
		line-height: $db-typography-normal-desktop-headline-3xlarge-line-height;
		font-size: $db-typography-normal-desktop-headline-3xlarge-font-size;}
}
```

We now get:
```SCSS
%db-desktop-3xlarge-lineHeight{

	line-height: $db-typography-desktop-mobile-3xlarge-lineHeight-line-height;
	font-size: $db-typography-desktop-mobile-3xlarge-lineHeight-font-size;

	--db-base-icon-font-size: #{$db-typography-desktop-mobile-3xlarge-lineHeight-font-size};
	--db-base-icon-font-family: #{get-icon-family($db-typography-desktop-mobile-3xlarge-lineHeight-font-size,
	$db-typography-desktop-mobile-3xlarge-lineHeight-line-height)};
	--db-base-icon-font-family-filled: #{get-icon-family($db-typography-desktop-mobile-3xlarge-lineHeight-font-size,
	$db-typography-desktop-mobile-3xlarge-lineHeight-line-height,"filled")};
	--db-type-body-font-size-lineHeight: #{$db-typography-desktop-mobile-3xlarge-lineHeight-font-size};
	--db-type-body-line-height-lineHeight: #{$db-typography-desktop-mobile-3xlarge-lineHeight-line-height};
		
	@media only screen and (min-width: $db-screens-md) {
		line-height: $db-typography-desktop-tablet-3xlarge-lineHeight-line-height;
		font-size: $db-typography-desktop-tablet-3xlarge-lineHeight-font-size;
		--db-base-icon-font-size: #{$db-typography-desktop-tablet-3xlarge-lineHeight-font-size};
		--db-base-icon-font-family: #{get-icon-family($db-typography-desktop-tablet-3xlarge-lineHeight-font-size,
		$db-typography-desktop-tablet-3xlarge-lineHeight-line-height)};
		--db-base-icon-font-family-filled: #{get-icon-family($db-typography-desktop-tablet-3xlarge-lineHeight-font-size,
		$db-typography-desktop-tablet-3xlarge-lineHeight-line-height,"filled")};
		--db-type-body-font-size-lineHeight: #{$db-typography-desktop-tablet-3xlarge-lineHeight-font-size};
		--db-type-body-line-height-lineHeight: #{$db-typography-desktop-tablet-3xlarge-lineHeight-line-height};
		}

	@media only screen and (min-width: $db-screens-lg) {
		line-height: $db-typography-desktop-desktop-3xlarge-lineHeight-line-height;
		font-size: $db-typography-desktop-desktop-3xlarge-lineHeight-font-size;
		--db-base-icon-font-size: #{$db-typography-desktop-desktop-3xlarge-lineHeight-font-size};
		--db-base-icon-font-family: #{get-icon-family($db-typography-desktop-desktop-3xlarge-lineHeight-font-size,
		$db-typography-desktop-desktop-3xlarge-lineHeight-line-height)};
		--db-base-icon-font-family-filled: #{get-icon-family($db-typography-desktop-desktop-3xlarge-lineHeight-font-size,
		$db-typography-desktop-desktop-3xlarge-lineHeight-line-height,"filled")};
		--db-type-body-font-size-lineHeight: #{$db-typography-desktop-desktop-3xlarge-lineHeight-font-size};
		--db-type-body-line-height-lineHeight: #{$db-typography-desktop-desktop-3xlarge-lineHeight-line-height};
		}
}
```

So this is mainly about the placeholder and variable names within like e.g. `$db-typography-desktop-mobile-3xlarge-lineHeight-line-height` that seem to be incorrect.
